<Project>

  <!-- Paths -->
  <PropertyGroup>
    <Root>$(MSBuildThisFileDirectory)</Root>
    <FrameworkCodeAnalysis>$(Root)..\code-analysis\</FrameworkCodeAnalysis>
  </PropertyGroup>

  <!-- Build Settings -->
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- Product Package Versions -->
  <PropertyGroup>
    <MicrosoftExtensionsVersion>10.0.12</MicrosoftExtensionsVersion>
  </PropertyGroup>

  <!-- Test Package Versions -->
  <PropertyGroup>
    <MicrosoftDotNetTestSdk>18.10.0</MicrosoftDotNetTestSdk>
    <MSTestVersion>4.4.0</MSTestVersion>
    <NSubstituteVersion>6.2.0</NSubstituteVersion>
    <FluentAssertionsVersion>8.10.0</FluentAssertionsVersion>
    <CoverletVersion>10.0.1</CoverletVersion>
  </PropertyGroup>

  <!-- Code Analyzer Versions -->
  <PropertyGroup>
    <CloudtoidCodeAnalysisVersion>1.0.28</CloudtoidCodeAnalysisVersion>
    <BannedApiAnalyzersVersion>5.6.0</BannedApiAnalyzersVersion>
  </PropertyGroup>

  <!-- Code Analyzer Packages -->
  <ItemGroup>
    <PackageReference Include="Cloudtoid.CodeAnalysis" Version="$(CloudtoidCodeAnalysisVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Code Analyzer Assets -->
  <ItemGroup>
    <AdditionalFiles Include="$(FrameworkCodeAnalysis)BannedSymbols.txt" Visible="false" />
  </ItemGroup>

  <!-- Package dependencies -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="$(BannedApiAnalyzersVersion)" IncludeAssets="all"/>
  </ItemGroup>

</Project>